import {
  numberPattern,
  integer,
  percentage,
  fraction,
  ratio,
  dimension,
  time,
  angle,
  frequency,
  resolution,
  length,
  enhancedRatio,
  unit,
  globalKeywords,
  numberWithUnit
} from './basic'

import { hexColor, colorFunction, namedColor, color } from './color'

import {
  cssFunction,
  cssCalcFunc,
  cssVariable,
  cssVariableUsage,
  transformProperty as transformFunctions,
  filterProperty as filterFunctions,
  backdropFilterFunctions
} from './cssFunctions'

import {
  cssValue,
  animationName,
  animationDuration,
  animationTimingFunction,
  animationDelay,
  animationIterationCount,
  animationDirection,
  animationFillMode,
  animationPlayState,
  gridLine,
  gridArea,
  gridTrackSize,
  gridTemplate,
  flexGrow,
  flexShrink,
  flexBasis,
  flexDirection,
  flexWrap,
  justifyContent,
  alignItems,
  alignContent,
  borderStyle,
  borderWidth,
  borderRadius,
  boxShadow,
  textShadow,
  fontWeight,
  fontSize,
  fontStyle,
  fontVariant,
  fontStretch,
  fontFamily
} from './cssValue'

import {
  identifier,
  propertyName,
  string,
  selector,
  mediaFeature,
  mediaQuery,
  containerQuery,
  dataUrl,
  httpUrl
} from './identifiers'

export const has = {
  // basic
  number: numberPattern,
  integer,
  percentage,
  fraction,
  ratio,
  dimension,
  time,
  angle,
  frequency,
  resolution,
  length,
  enhancedRatio,
  unit,
  globalKeywords,
  numberWithUnit,

  // color
  hexColor,
  colorFunction,
  namedColor,
  color,

  // css functions
  cssFunction,
  cssCalcFunc,
  cssVariable,
  cssVariableUsage,
  transformFunctions,
  filterFunctions,
  backdropFilterFunctions,

  // css value
  cssValue,
  animationName,
  animationDuration,
  animationTimingFunction,
  animationDelay,
  animationIterationCount,
  animationDirection,
  animationFillMode,
  animationPlayState,
  gridLine,
  gridArea,
  gridTrackSize,
  gridTemplate,
  flexGrow,
  flexShrink,
  flexBasis,
  flexDirection,
  flexWrap,
  justifyContent,
  alignItems,
  alignContent,
  borderStyle,
  borderWidth,
  borderRadius,
  boxShadow,
  textShadow,
  fontWeight,
  fontSize,
  fontStyle,
  fontVariant,
  fontStretch,
  fontFamily,

  // identifiers
  identifier,
  propertyName,
  string,
  selector,
  mediaFeature,
  mediaQuery,
  containerQuery,
  dataUrl,
  httpUrl
}
