export * from './basic'
export * from './color'
export * from './cssValue'
export * from './identifiers'
export * from './cssFunctions'
export { has } from './has'
export { specificFunctions as hasFunction } from './cssFunctions'
export { is, isFunction } from './is'
